### ISSUE TITLE
More of a question than an issue. Stand alone?

### ISSUE THREAD

**Issue by darrinps** [Jertlok/Recordie#3]
@Jertlok Wondering if you were thinking of splitting the recorder functionality apart from the UI so that other apps could use it. It works nicely and think others might be able to use the recording portion if it could be easily called (a library....start recording with these settings...stop recording) from within their code. Make it available with a simple Gradle inclusion. I could see this used quite a bit.

**Comment by Jertlok** [comment]
I don't think it would be worth it, Google's MediaProjection API is pretty simple to use.
Anyhow, thanks for your suggestion :)
